// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

package com.hamdaankhalid.grpc;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Heartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string leaderId = 1;</code>
   * @return The leaderId.
   */
  java.lang.String getLeaderId();
  /**
   * <code>string leaderId = 1;</code>
   * @return The bytes for leaderId.
   */
  com.google.protobuf.ByteString
      getLeaderIdBytes();
}
