// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

package com.hamdaankhalid.grpc;

public final class Raft {
  private Raft() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRaft.proto\"\035\n\tHeartbeat\022\020\n\010leaderId\030\001 " +
      "\001(\t\"0\n\013VoteRequest\022\014\n\004term\030\001 \001(\005\022\023\n\013cand" +
      "idateId\030\002 \001(\t\"1\n\014VoteResponse\022\014\n\004term\030\001 " +
      "\001(\005\022\023\n\013voteGranted\030\002 \001(\0102k\n\013RaftService\022" +
      "-\n\014requestVotes\022\014.VoteRequest\032\r.VoteResp" +
      "onse\"\000\022-\n\021leaderSentMessage\022\n.Heartbeat\032" +
      "\n.Heartbeat\"\000B\032\n\026com.hamdaankhalid.grpcP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Heartbeat_descriptor,
        new java.lang.String[] { "LeaderId", });
    internal_static_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteRequest_descriptor,
        new java.lang.String[] { "Term", "CandidateId", });
    internal_static_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteResponse_descriptor,
        new java.lang.String[] { "Term", "VoteGranted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
