// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Raft.proto

package com.hamdaankhalid.grpc;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 term = 1;</code>
   * @return The term.
   */
  int getTerm();

  /**
   * <code>string candidateId = 2;</code>
   * @return The candidateId.
   */
  java.lang.String getCandidateId();
  /**
   * <code>string candidateId = 2;</code>
   * @return The bytes for candidateId.
   */
  com.google.protobuf.ByteString
      getCandidateIdBytes();
}
